<?php

namespace Likemusic\BamboraCheckout\Parameters\Parts;

/**
 * @see https://dev.na.bambora.com/docs/references/checkout/#authorization
 */
interface AuthorizationParameters
{
    const MERCHANT_ID = 'merchant_id'; // Your 9-digit Bambora merchant ID
    const HASH_VALUE = 'hashValue'; // The value for hashValue is generated by appending a hash key to the transaction
    // request query string and using a hash algorithm (either MD5 or SHA-1) on the resulting string.
}
